// src/services/aiService.js

import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";
dotenv.config();

const apiKey = process.env.GEMINI_API_KEY;
const MODEL_NAME = "gemini-2.5-flash"; // Recommended model for speed and efficiency

if (!apiKey) {
  // Throws an error if the key is missing, stops the server in advance
  throw new Error("GEMINI_API_KEY is not set in environment variables.");
}

// Creating an instance of the AI Client
const ai = new GoogleGenAI({ apiKey });

// --- 1. AI Book Summary ---
function isHebrew(text = "") {
  return /[\u0590-\u05FF]/.test(text);
}
/**
 * Creates a short summary for a book using Gemini.
 * @param {string} title - Book title.
 * @param {string} author - Author name.
 * @param {string} description - Short description from the user.
 * @returns {Promise<string>} Summary generated by AI.
 */
export async function generateBookSummary(title, author, description) {
  const prompt = `
        You will receive a book title, author, and description.
    Detect the dominant language silently and use it to write the summary.

    IMPORTANT:
    - Do NOT explain the language you detected.
    - Do NOT mention detection results.
    - Output ONLY the final summary, nothing else.

        Create a concise and engaging summary (2-3 sentences) for the book titled:
        "${title}" by "${author}".
        Use the following book description as reference: "${description},
        and search the internet for additional context if needed.
        Make sure the summary is clear and well-written.
    `;

  try {
    //  Corrected call according to documentation
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: {
        temperature: 0.7, // creativity level
      },
    });

    return response.text.trim();
  } catch (error) {
    console.error("Gemini Summary Error:", error);
    const combinedText = `${title} ${author} ${description}`;
    const hebrew = isHebrew(combinedText);

    return hebrew
      ? `${title} מאת ${author}מציע חוויית קריאה מסקרנת ומשלב תוכן המעודד הבנה והעמקה.
מתאים לקוראים המחפשים קריאה משמעותית וברורה.`
      : `${title} by ${author} is offers an engaging reading experience while encouraging understanding and thoughtful reflection.
Suitable for readers seeking a meaningful and clear read.`;
  }
}

// --- 2. AI Recommendations ---

/**
 * Provides book recommendations based on a list of favorite books.
 * @param {Array<Object>} favoriteBooks - User's favorite books list (with title fields).
 * @param {Array<Object>} candidateBooks - List of available books in the system (with id, title, author fields).
 * @returns {Promise<Array<Object>>} List of recommendations (up to 5) in JSON format.
 */
export async function getBookRecommendations(favoriteBooks, candidateBooks) {
  const prompt = `
  You are an expert librarian and book matchmaker.
  
  User's reading history (Favorite Books):
  ${JSON.stringify(favoriteBooks, null, 2)}

  Available library books (Candidates):
  ${JSON.stringify(candidateBooks, null, 2)}

  Instructions:
  1. Select up to 5 books from the "Available library books" that best match the user's taste.
  2. Explain WHY you chose each book.
  3. Provide the reason in TWO languages: English ('en') and Hebrew ('he').
  4. IMPORTANT: The Hebrew reason must sound natural, warm, and native (not a direct Google Translate style).

  Output Format:
  Return ONLY a raw JSON object with this exact structure:
  {
    "recommendations": [ 
      { 
        "id": "string (original book id)", 
        "reason": {
          "en": "Explanation in English",
          "he": "הסבר בעברית שנשמע טבעי וזורם"
        } 
      } 
    ]
  }
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const result = JSON.parse(response.text.trim());
    return result.recommendations;
  } catch (error) {
    console.error("Gemini Recommendation Error:", error);
    return candidateBooks.slice(0, 5).map((book) => ({
      id: book.id,
      reason: {
        en: "This book was selected because its general themes and subject matter align well with the reader’s interests, offering a natural continuation of their reading preferences.",
        he: "הספר נבחר בזכות הנושאים והכיוון הכללי שלו, שמשתלבים היטב עם תחומי העניין המשתקפים מהקריאה הקודמת, ומהווים המשך טבעי לחוויית הקריאה.",
      },
    }));
  }
}
