// src/services/aiService.js

import { GoogleGenAI } from '@google/genai';
import 'dotenv/config'; // Modern method for loading .env (if you haven't used import dotenv)

const apiKey = process.env.GEMINI_API_KEY;
const MODEL_NAME = "gemini-2.5-flash"; // Recommended model for speed and efficiency

if (!apiKey) {
    // Throws an error if the key is missing, stops the server in advance
    throw new Error("GEMINI_API_KEY is not set in environment variables.");
}

// Creating an instance of the AI Client
const ai = new GoogleGenAI({ apiKey });

// --- 1. AI Book Summary ---

/**
 * Creates a short summary for a book using Gemini.
 * @param {string} title - Book title.
 * @param {string} author - Author name.
 * @param {string} description - Short description from the user.
 * @returns {Promise<string>} Summary generated by AI.
 */
export async function generateBookSummary(title, author, description) {
    const prompt = `
        Create a concise and engaging summary (2-3 sentences) for the book titled:
        "${title}" by "${author}".
        Use the following book description as reference: "${description}".
        Make sure the summary is clear and well-written.
    `;

    try {
        // ✅ Corrected call according to documentation
        const response = await ai.models.generateContent({
             model: MODEL_NAME,
             contents: prompt,
             config: { 
                 temperature: 0.7 // creativity level
             }
        });
        
        return response.text.trim();
        
    } catch (error) {
        console.error("Gemini Summary Error:", error);
        return "AI summary is not available at the moment."; // default value in case of error
    }
}

// --- 2. AI Recommendations ---

/**
 * Provides book recommendations based on a list of favorite books.
 * @param {Array<Object>} favoriteBooks - User's favorite books list (with title fields).
 * @param {Array<Object>} candidateBooks - List of available books in the system (with id, title, author fields).
 * @returns {Promise<Array<Object>>} List of recommendations (up to 5) in JSON format.
 */
// export async function getBookRecommendations(favoriteBooks) {
//     // Creating a comma-separated list of book titles
//     const bookTitles = favoriteBooks.map(book => book.title).join(', ');
    
//     // Instructions for Gemini to work in JSON format
//     const prompt = `
//         The user likes the following books: ${bookTitles}. 
//         Suggest 5 similar book recommendations (book title and author) that match the style, genre and theme of the books they like.
//         Provide the result in JSON format only.
//     `;

//     try {
//         // ✅ Corrected call for Gemini JSON Mode
//         const response = await ai.models.generateContent({
//              model: MODEL_NAME,
//              contents: prompt,
//              config: {
//                  responseMimeType: "application/json", 
//                  responseSchema: { // Expected JSON structure definition
//                      type: "object",
//                      properties: {
//                          recommendations: {
//                              type: "array",
//                              items: {
//                                  type: "object",
//                                  properties: {
//                                      title: { type: "string" },
//                                      author: { type: "string" }
//                                  },
//                                  required: ["title", "author"]
//                              }
//                          }
//                      },
//                      required: ["recommendations"]
//                  }
//              }
//         });

//         // Parse JSON output
//         const jsonText = response.text.trim();
//         const result = JSON.parse(jsonText);
//         return result.recommendations;

//     } catch (error) {
//         console.error("Gemini Recommendation Error:", error);
//         return [];
//     }
// }
export async function getBookRecommendations(favoriteBooks, candidateBooks) {
  const prompt = `
  The user liked the following books:
  ${JSON.stringify(favoriteBooks, null, 2)}

  Here are the books available in the system:
  ${JSON.stringify(candidateBooks, null, 2)}

  Choose up to 5 books only from the candidate list.
  Return in JSON format:
  {
    "recommendations": [ { "id": "string", "reason": "string" } ]
  }
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: {
        responseMimeType: "application/json"
      }
    });

    const result = JSON.parse(response.text.trim());
    return result.recommendations;

  } catch (error) {
    console.error("Gemini Recommendation Error:", error);
    return [];
  }
}
